services:
  db:
    image: mysql:8
    container_name: concurso_db
    environment:
      MYSQL_USER: concurso_user
      MYSQL_PASSWORD: concurso_password
      MYSQL_DATABASE: concurso_db
      MYSQL_ROOT_PASSWORD: root_password_segura
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
